name: Build PDF (Pandoc)

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      enable_deploy:
        description: "Habilitar a implantação? (true/false)"
        required: true
        default: "false"

jobs:
  build-pandoc:
    runs-on: ubuntu-latest
    container:
      image: docker://reinanhs/limarka:20.7.13.pre.365-alpine-v3.22-base
    steps:
      - uses: actions/checkout@v4

      - name: Run Commands
        run: |
          pandoc -s main.md -o arquivo.pdf --template=template.tex --bibliography=referencias.bib --biblatex --pdf-engine=latexmk || true
      - name: Archive pandoc artifacts
        uses: actions/upload-artifact@v4
        with:
          name: arquivo.pdf
          path: arquivo.pdf
          retention-days: 7
